Repository OrcaBus/platform-cdk-constructs, pull requests merged in 2025-07, with the labels that each got.

#81 fix: add missing SNS notification for alarms
  packages/docs/@orcabus/namespaces/monitoredQueue/classes/MonitoredQueue.md
  packages/monitored-queue/README.md
  packages/monitored-queue/index.ts
Labels: bug

#85 Orcabus api tools fixes
  packages/lambda/layers/orcabus_api_tools/src/orcabus_api_tools/data_sharing/__init__.py
  packages/lambda/layers/orcabus_api_tools/src/orcabus_api_tools/data_sharing/globals.py
  packages/lambda/layers/orcabus_api_tools/src/orcabus_api_tools/data_sharing/models.py
  packages/lambda/layers/orcabus_api_tools/src/orcabus_api_tools/data_sharing/update_helpers.py
  packages/lambda/layers/orcabus_api_tools/src/orcabus_api_tools/fastq/__init__.py
  packages/lambda/layers/orcabus_api_tools/src/orcabus_api_tools/fastq/create_helpers.py
  packages/lambda/layers/orcabus_api_tools/src/orcabus_api_tools/fastq/globals.py
  packages/lambda/layers/orcabus_api_tools/src/orcabus_api_tools/fastq/job_helpers.py
  packages/lambda/layers/orcabus_api_tools/src/orcabus_api_tools/fastq/models.py
  packages/lambda/layers/orcabus_api_tools/src/orcabus_api_tools/fastq/query_helpers.py
  packages/lambda/layers/orcabus_api_tools/src/orcabus_api_tools/fastq/update_helpers.py
  packages/lambda/layers/orcabus_api_tools/src/orcabus_api_tools/fastq/workflow_helpers.py
  packages/lambda/layers/orcabus_api_tools/src/orcabus_api_tools/fastq_unarchiving/__init__.py
  packages/lambda/layers/orcabus_api_tools/src/orcabus_api_tools/fastq_unarchiving/create_helpers.py
  packages/lambda/layers/orcabus_api_tools/src/orcabus_api_tools/fastq_unarchiving/globals.py
  packages/lambda/layers/orcabus_api_tools/src/orcabus_api_tools/fastq_unarchiving/models.py
  packages/lambda/layers/orcabus_api_tools/src/orcabus_api_tools/fastq_unarchiving/query_helpers.py
  packages/lambda/layers/orcabus_api_tools/src/orcabus_api_tools/fastq_unarchiving/update_helpers.py
  packages/lambda/layers/orcabus_api_tools/src/orcabus_api_tools/filemanager/__init__.py
  packages/lambda/layers/orcabus_api_tools/src/orcabus_api_tools/filemanager/file_helpers.py
  packages/lambda/layers/orcabus_api_tools/src/orcabus_api_tools/filemanager/globals.py
  packages/lambda/layers/orcabus_api_tools/src/orcabus_api_tools/filemanager/models.py
  packages/lambda/layers/orcabus_api_tools/src/orcabus_api_tools/utils/requests_helpers.py
Labels: enhancement

#86 Updated fastq decompression create job
  packages/lambda/layers/orcabus_api_tools/src/orcabus_api_tools/fastq/models.py
  packages/lambda/layers/orcabus_api_tools/src/orcabus_api_tools/fastq_decompression/create_helpers.py
  packages/lambda/layers/orcabus_api_tools/src/orcabus_api_tools/fastq_decompression/models.py
  packages/lambda/layers/orcabus_api_tools/src/orcabus_api_tools/filemanager/models.py
Labels: enhancement

#87 Use json over params for patch and post requests
  packages/lambda/layers/orcabus_api_tools/src/orcabus_api_tools/fastq_decompression/__init__.py
  packages/lambda/layers/orcabus_api_tools/src/orcabus_api_tools/fastq_decompression/create_helpers.py
  packages/lambda/layers/orcabus_api_tools/src/orcabus_api_tools/fastq_decompression/models.py
  packages/lambda/layers/orcabus_api_tools/src/orcabus_api_tools/fastq_decompression/query_helpers.py
  packages/lambda/layers/orcabus_api_tools/src/orcabus_api_tools/fastq_decompression/update_helpers.py
  packages/lambda/layers/orcabus_api_tools/src/orcabus_api_tools/fastq_unarchiving/__init__.py
  packages/lambda/layers/orcabus_api_tools/src/orcabus_api_tools/fastq_unarchiving/update_helpers.py
  packages/lambda/layers/orcabus_api_tools/src/orcabus_api_tools/utils/requests_helpers.py
Labels: enhancement

#88 Migrate to json_data for fastq and icav2 wes patch and post parameters
  packages/lambda/layers/mart_tools/src/mart_tools/mart/models.py
  packages/lambda/layers/orcabus_api_tools/src/orcabus_api_tools/data_sharing/__init__.py
  packages/lambda/layers/orcabus_api_tools/src/orcabus_api_tools/data_sharing/globals.py
  packages/lambda/layers/orcabus_api_tools/src/orcabus_api_tools/data_sharing/models.py
  packages/lambda/layers/orcabus_api_tools/src/orcabus_api_tools/data_sharing/update_helpers.py
  packages/lambda/layers/orcabus_api_tools/src/orcabus_api_tools/fastq/__init__.py
  packages/lambda/layers/orcabus_api_tools/src/orcabus_api_tools/fastq/create_helpers.py
  packages/lambda/layers/orcabus_api_tools/src/orcabus_api_tools/fastq/models.py
  packages/lambda/layers/orcabus_api_tools/src/orcabus_api_tools/fastq/update_helpers.py
  packages/lambda/layers/orcabus_api_tools/src/orcabus_api_tools/fastq_decompression/globals.py
  packages/lambda/layers/orcabus_api_tools/src/orcabus_api_tools/fastq_decompression/update_helpers.py
  packages/lambda/layers/orcabus_api_tools/src/orcabus_api_tools/icav2_wes/__init__.py
  packages/lambda/layers/orcabus_api_tools/src/orcabus_api_tools/icav2_wes/create_helpers.py
  packages/lambda/layers/orcabus_api_tools/src/orcabus_api_tools/icav2_wes/models.py
  packages/lambda/layers/orcabus_api_tools/src/orcabus_api_tools/icav2_wes/update_helpers.py
  packages/lambda/layers/orcabus_api_tools/src/orcabus_api_tools/mart/models.py
  packages/lambda/layers/orcabus_api_tools/src/orcabus_api_tools/metadata/project_helpers.py
  packages/lambda/layers/orcabus_api_tools/src/orcabus_api_tools/metadata/sample_helpers.py
  packages/lambda/layers/orcabus_api_tools/src/orcabus_api_tools/metadata/subject_helpers.py
  packages/lambda/layers/orcabus_api_tools/src/orcabus_api_tools/sequence/models.py
  packages/lambda/layers/orcabus_api_tools/src/orcabus_api_tools/utils/requests_helpers.py
Labels: enhancement

#90 Simplify the filemanager logic to get files when given a portal run id
  packages/lambda/layers/orcabus_api_tools/src/orcabus_api_tools/data_sharing/models.py
  packages/lambda/layers/orcabus_api_tools/src/orcabus_api_tools/filemanager/file_helpers.py
Labels: bug, enhancement

#91 Added the get by rgid command
  packages/lambda/layers/orcabus_api_tools/src/orcabus_api_tools/fastq/__init__.py
  packages/lambda/layers/orcabus_api_tools/src/orcabus_api_tools/fastq/globals.py
  packages/lambda/layers/orcabus_api_tools/src/orcabus_api_tools/fastq/query_helpers.py
  packages/lambda/layers/orcabus_api_tools/src/orcabus_api_tools/fastq/update_helpers.py
Labels: enhancement

#95 Added in sequali reporting model
  packages/lambda/layers/orcabus_api_tools/src/orcabus_api_tools/fastq/models.py
Labels: enhancement

#99 Layer should be at scope level as is shared across lambdas
  packages/lambda/index.ts
Labels: bug, enhancement

#106 ReadCountCalculation object should be a separate class in models
  packages/lambda/layers/orcabus_api_tools/src/orcabus_api_tools/fastq_decompression/models.py
Labels: bug

#108 Update sequence run helpers to new endpoints
  packages/lambda/layers/orcabus_api_tools/src/orcabus_api_tools/sequence/__init__.py
  packages/lambda/layers/orcabus_api_tools/src/orcabus_api_tools/sequence/globals.py
  packages/lambda/layers/orcabus_api_tools/src/orcabus_api_tools/sequence/models.py
  packages/lambda/layers/orcabus_api_tools/src/orcabus_api_tools/sequence/sequence_helpers.py
Labels: bug

#110 Correctly parse booleans in params
  packages/lambda/layers/orcabus_api_tools/src/orcabus_api_tools/fastq/query_helpers.py
  packages/lambda/layers/orcabus_api_tools/src/orcabus_api_tools/utils/requests_helpers.py
Labels: bug

#113 Add wrapica dev release to icav2 toolkit layer
  packages/lambda/layers/icav2_tools/poetry.lock
  packages/lambda/layers/icav2_tools/pyproject.toml
Labels: enhancement

#114 Add primary and secondary sources to toml
  packages/lambda/layers/icav2_tools/poetry.lock
  packages/lambda/layers/icav2_tools/pyproject.toml
Labels: bug

#116 Update icav2-toolkit poetry lock file
  packages/lambda/layers/icav2_tools/poetry.lock
Labels: bug
